import { notFound } from 'next/navigation';
import type { Metadata } from 'next';
import { getSql } from '@/lib/db';
import SavedBeatdownClient from './SavedBeatdownClient';
import type { BeatdownInputs, BeatdownSections } from '@/types/beatdown';

interface Row {
  short_id: string;
  title: string;
  inputs: BeatdownInputs;
  sections: BeatdownSections;
  generation_model: string;
  generation_ms: number;
  created_at: string;
}

export async function generateMetadata({ params }: { params: Promise<{ short_id: string }> }): Promise<Metadata> {
  const { short_id } = await params;

  let rows: { title: string; inputs: BeatdownInputs }[] = [];
  try {
    const sql = getSql();
    rows = (await sql`
      SELECT title, inputs FROM beatdowns WHERE short_id = ${short_id} LIMIT 1
    `) as { title: string; inputs: BeatdownInputs }[];
  } catch (error) {
    console.error('[beatdown:saved] metadata lookup failed:', error);
  }

  if (rows.length === 0) return { title: 'Beatdown not found' };
  return {
    title: `${rows[0].title} · F3 Marietta Beatdown`,
    description: `${rows[0].inputs.ao_display_name ? `${rows[0].inputs.ao_display_name} beatdown` : 'Beatdown'} — generated by the F3 Marietta AI Beatdown Builder`,
  };
}

export default async function SavedBeatdownPage({ params }: { params: Promise<{ short_id: string }> }) {
  const { short_id } = await params;
  if (!/^[a-z0-9]{8}$/.test(short_id)) notFound();

  // Graceful-degradation contract shared by the page data loaders: a database
  // failure renders not-found rather than a 500. A shared beatdown link is
  // handed around Slack, so a Neon blip should show "not found", not a crash.
  // notFound() throws a control-flow signal, so it stays outside the try.
  let rows: Row[] = [];
  try {
    const sql = getSql();
    rows = (await sql`
      SELECT short_id, title, inputs, sections, generation_model, generation_ms, created_at
      FROM beatdowns
      WHERE short_id = ${short_id}
      LIMIT 1
    `) as Row[];
  } catch (error) {
    console.error('[beatdown:saved] lookup failed:', error);
  }

  if (rows.length === 0) notFound();
  return <SavedBeatdownClient row={rows[0]} />;
}
