import { notFound } from 'next/navigation';
import type { Metadata } from 'next';
import { getSql } from '@/lib/db';
import SavedBeatdownClient from './SavedBeatdownClient';
import type { BeatdownInputs, BeatdownSections } from '@/types/beatdown';

interface Row {
  short_id: string;
  title: string;
  inputs: BeatdownInputs;
  sections: BeatdownSections;
  generation_model: string;
  generation_ms: number;
  created_at: string;
}

export async function generateMetadata({ params }: { params: Promise<{ short_id: string }> }): Promise<Metadata> {
  const { short_id } = await params;
  const sql = getSql();
  const rows = await sql`SELECT title, inputs FROM beatdowns WHERE short_id = ${short_id} LIMIT 1` as { title: string; inputs: BeatdownInputs }[];
  if (rows.length === 0) return { title: 'Beatdown not found' };
  return {
    title: `${rows[0].title} · F3 Marietta Beatdown`,
    description: `${rows[0].inputs.ao_display_name ? `${rows[0].inputs.ao_display_name} beatdown` : 'Beatdown'} — generated by the F3 Marietta AI Beatdown Builder`,
  };
}

export default async function SavedBeatdownPage({ params }: { params: Promise<{ short_id: string }> }) {
  const { short_id } = await params;
  if (!/^[a-z0-9]{8}$/.test(short_id)) notFound();
  const sql = getSql();
  const rows = await sql`
    SELECT short_id, title, inputs, sections, generation_model, generation_ms, created_at
    FROM beatdowns
    WHERE short_id = ${short_id}
    LIMIT 1
  ` as Row[];
  if (rows.length === 0) notFound();
  return <SavedBeatdownClient row={rows[0]} />;
}
